apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-failed
    helm.sh/hook-weight: "40"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kustomize.toolkit.fluxcd.io/v1beta1","kind":"Kustomization","metadata":{"annotations":{"kustomize.toolkit.fluxcd.io/checksum":"a14dac790ac090c21e3097408d1b1b930db37b8c"},"creationTimestamp":null,"labels":{"kustomize.toolkit.fluxcd.io/name":"management-cluster","kustomize.toolkit.fluxcd.io/namespace":"kommander"},"name":"kommander-flux","namespace":"kommander"},"spec":{"interval":"15s","patchesJson6902":[{"patch":[{"op":"replace","path":"/metadata/name","value":"kommander-flux"},{"op":"add","path":"/metadata/labels","value":{"kommander.d2iq.io/managed-by-kind":"AppDeployment"}}],"target":{"kind":"HelmRelease","name":"kommander-flux"}}],"path":"./services/kommander-flux/0.17.2","postBuild":{"substitute":{"releaseNamespace":"kommander","traefikNamespace":"kommander","workspaceNamespace":"kommander"},"substituteFrom":[{"kind":"ConfigMap","name":"substitution-vars"},{"kind":"ConfigMap","name":"kommander-vars"},{"kind":"ConfigMap","name":"helm-repository-vars"}]},"prune":true,"sourceRef":{"kind":"GitRepository","name":"management","namespace":"kommander-flux"}},"status":{}}
    kustomize.toolkit.fluxcd.io/checksum: a14dac790ac090c21e3097408d1b1b930db37b8c
  creationTimestamp: "2021-11-09T19:20:35Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: management-cluster
    kustomize.toolkit.fluxcd.io/namespace: kommander
  managedFields:
  - apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:helm.sh/hook: {}
          f:helm.sh/hook-delete-policy: {}
          f:helm.sh/hook-weight: {}
      f:spec:
        .: {}
        f:force: {}
        f:interval: {}
        f:patchesJson6902: {}
        f:path: {}
        f:postBuild:
          .: {}
          f:substitute:
            .: {}
            f:namespace: {}
            f:releaseNamespace: {}
            f:traefikNamespace: {}
            f:workspaceNamespace: {}
          f:substituteFrom: {}
        f:prune: {}
        f:sourceRef:
          .: {}
          f:kind: {}
          f:name: {}
          f:namespace: {}
    manager: helm
    operation: Update
    time: "2021-11-09T19:20:35Z"
  - apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:kustomize.toolkit.fluxcd.io/checksum: {}
        f:finalizers:
          .: {}
          v:"finalizers.fluxcd.io": {}
        f:labels:
          .: {}
          f:kustomize.toolkit.fluxcd.io/name: {}
          f:kustomize.toolkit.fluxcd.io/namespace: {}
      f:status:
        f:conditions: {}
        f:lastAppliedRevision: {}
        f:lastAttemptedRevision: {}
        f:observedGeneration: {}
        f:snapshot:
          .: {}
          f:checksum: {}
          f:entries: {}
    manager: kustomize-controller
    operation: Update
    time: "2021-11-09T19:21:49Z"
  name: kommander-flux
  namespace: kommander
  resourceVersion: "264189"
  uid: 4227d164-2318-4645-b3bb-22e009396cf4
spec:
  force: false
  interval: 15s
  patchesJson6902:
  - patch:
    - op: replace
      path: /metadata/name
      value: kommander-flux
    - op: add
      path: /metadata/labels
      value:
        kommander.d2iq.io/managed-by-kind: AppDeployment
    target:
      kind: HelmRelease
      name: kommander-flux
  path: ./services/kommander-flux/0.17.2
  postBuild:
    substitute:
      namespace: kommander
      releaseNamespace: kommander
      traefikNamespace: kommander
      workspaceNamespace: kommander
    substituteFrom:
    - kind: ConfigMap
      name: substitution-vars
    - kind: ConfigMap
      name: kommander-vars
    - kind: ConfigMap
      name: helm-repository-vars
  prune: true
  sourceRef:
    kind: GitRepository
    name: management
    namespace: kommander-flux
status:
  conditions:
  - lastTransitionTime: "2021-11-09T23:09:37Z"
    message: 'Applied revision: master/f32736e151df3c9302454ca2a08940d3b7d86478'
    reason: ReconciliationSucceeded
    status: "True"
    type: Ready
  lastAppliedRevision: master/f32736e151df3c9302454ca2a08940d3b7d86478
  lastAttemptedRevision: master/f32736e151df3c9302454ca2a08940d3b7d86478
  observedGeneration: 1
  snapshot:
    checksum: 0d0cdaea520458c688e73813f3df63b0a55e80a5
    entries:
    - kinds:
        apiextensions.k8s.io/v1, Kind=CustomResourceDefinition: CustomResourceDefinition
        rbac.authorization.k8s.io/v1, Kind=ClusterRole: ClusterRole
        rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding: ClusterRoleBinding
      namespace: ""
    - kinds:
        /v1, Kind=Service: Service
        /v1, Kind=ServiceAccount: ServiceAccount
        apps/v1, Kind=Deployment: Deployment
        networking.k8s.io/v1, Kind=NetworkPolicy: NetworkPolicy
      namespace: kommander-flux
